### ISSUE TITLE
Would you please tell me where I can find the data?

### ISSUE THREAD

**Issue by xu-cpp** [gentaiscool/lstm-attention#1]
Would you please tell me where I can find the data?

**Comment by gentaiscool** [comment]
@xu-cpp I plan to release the dataset in this repository within this week. I will let you know when it is ready.

**Comment by xu-cpp** [comment]
It's great to hear from you. Appreciate that.

**Comment by gentaiscool** [comment]
@xu-cpp I just uploaded the data to the repository.

**Comment by xu-cpp** [comment]
Thanks!
